{:user {:plugins [[lein-localrepo "0.5.2"]
                  [lein-pprint "1.1.1"]
                  [lein-ancient "0.5.4"]
                  [lein-immutant "1.2.0"]
                  [lein-marginalia "0.7.1"]
                  [lein-midje "3.1.3"]
                  [lein-tar "3.0.0"]
                  [lein-cljsbuild "1.0.2"]
                  [lein-cucumber "1.0.2"]]
        :dependencies [[alembic "0.2.0"]]}}
